In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pylab as plt

In [2]:
!ls data

a-large-tennis-dataset-for-atp-and-itf-betting.zip  betting_moneyline.csv
all_matches.csv					    betting_spreads.csv
all_players.csv					    betting_totals.csv
all_tournaments.csv				    countries.csv

In [3]:
reader = pd.read_csv('./data/all_matches.csv', chunksize=100)

In [4]:
reader.get_chunk(5)

   start_date    end_date  location court_surface  prize_money currency  year                      player_id   player_name                  opponent_id    ...    total_points  duration player_victory  retirement  seed  won_first_set  doubles  masters  round_num    nation
0  2012-06-11  2012-06-17  Slovakia          Clay        30000        €  2012                   adrian-partl      A. Partl                andrej-martin    ...            88.0  01:02:00              f           f   NaN              f        f      100          1  Slovakia
1  2012-06-11  2012-06-17  Slovakia          Clay        30000        €  2012                   adrian-partl      A. Partl                jozef-kovalik    ...           195.0  02:43:00              t           f   NaN              t        f      100          0  Slovakia
2  2012-06-11  2012-06-17  Slovakia          Clay        30000        €  2012                agustin-velotti    A. Velotti               dominik-hrbaty    ...           126.0  01:17:00              f           f   NaN              f        f      100          3  Slovakia
3  2012-06-11  2012-06-17  Slovakia          Clay        30000        €  2012  agustin-velotti_marcel-felder           NaN  andrei-daescu_florin-mergea    ...             NaN       NaN              f           f   NaN              t        t      100          4  Slovakia
4  2012-06-11  2012-06-17  Slovakia          Clay        30000        €  2012           alessandro-giannessi  A. Giannessi             harri-heliovaara    ...           194.0  02:32:00              t           f   1.0              t        f      100          3  Slovakia

[5 rows x 54 columns]

In [7]:
def preprocess(df):
    
    df = df.drop(['start_date', 'end_date', 'location', 'prize_money', 'currency', 'player_id', 'opponent_id', 'duration', 'seed', 'nation'], axis=1)
    df = df[df['doubles'] == 'f']
    df = df[df['year'] >= 2017]
    return df

df_matches = pd.concat((preprocess(r) for r in reader), ignore_index=True)

In [19]:
len(df_matches)

296386